// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approve.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendingApprovals = `-- name: ListPendingApprovals :many
select aw.id, r.id as request_id, u.first_name || ' ' || u.last_name as applicant_name, res.name as resource_name, r.access_type, r.access_reason, aw.status, aw.created_at
from approval_workflow aw
join requests r on aw.request_id = r.id
join users u on r.applicant_id = u.id
join resources res on r.resource_id = res.id
where aw.approver_id = $1 and aw.status = 'pending'
order by aw.created_at
`

type ListPendingApprovalsRow struct {
	ID            int32
	RequestID     int32
	ApplicantName interface{}
	ResourceName  string
	AccessType    string
	AccessReason  string
	Status        string
	CreatedAt     pgtype.Date
}

func (q *Queries) ListPendingApprovals(ctx context.Context, approverID pgtype.Int4) ([]ListPendingApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listPendingApprovals, approverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingApprovalsRow
	for rows.Next() {
		var i ListPendingApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ApplicantName,
			&i.ResourceName,
			&i.AccessType,
			&i.AccessReason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalStatus = `-- name: UpdateApprovalStatus :exec
update approval_workflow
set status = $1
where id = $2
`

type UpdateApprovalStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateApprovalStatus(ctx context.Context, arg UpdateApprovalStatusParams) error {
	_, err := q.db.Exec(ctx, updateApprovalStatus, arg.Status, arg.ID)
	return err
}
