// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (username, email, password_hash, first_name, last_name, department_id)
values ($1, $2, $3, $4, $5, $6) returning id, username, email, password_hash, first_name, last_name, department_id, is_active, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	DepartmentID pgtype.Int4
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.DepartmentID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, email, password_hash, first_name, last_name, department_id, is_active, created_at from users where username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
select r.code from roles r
join user_roles ur on r.id = ur.role_id
where ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const giveUserRole = `-- name: GiveUserRole :exec
insert into user_roles (user_id, role_id) values ($1, $2)
`

type GiveUserRoleParams struct {
	UserID int32
	RoleID int32
}

func (q *Queries) GiveUserRole(ctx context.Context, arg GiveUserRoleParams) error {
	_, err := q.db.Exec(ctx, giveUserRole, arg.UserID, arg.RoleID)
	return err
}
