// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
insert into users (username, email, password_hash, first_name, last_name, department_id, manager_id, job_title)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, username, email, password_hash, first_name, last_name, department_id, manager_id, job_title, is_active, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	DepartmentID int32
	ManagerID    pgtype.Int4
	JobTitle     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.DepartmentID,
		arg.ManagerID,
		arg.JobTitle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.JobTitle,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getManagerID = `-- name: GetManagerID :one
select manager_id from users where id = $1
`

func (q *Queries) GetManagerID(ctx context.Context, id int32) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getManagerID, id)
	var manager_id pgtype.Int4
	err := row.Scan(&manager_id)
	return manager_id, err
}

const getSecurityEmployeesID = `-- name: GetSecurityEmployeesID :many
select user_id from user_roles where role_id = (select id from roles where code = 'security')
`

func (q *Queries) GetSecurityEmployeesID(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, getSecurityEmployeesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, username, email, password_hash, first_name, last_name, department_id, manager_id, job_title, is_active, created_at from users where username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentID,
		&i.ManagerID,
		&i.JobTitle,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInfoByID = `-- name: GetUserInfoByID :one
select u.first_name || ' ' || u.last_name, u.email, u.job_title, d.name as department_name
from users u
left join departments d on u.department_id = d.id
where u.id = $1
`

type GetUserInfoByIDRow struct {
	Column1        interface{}
	Email          string
	JobTitle       pgtype.Text
	DepartmentName pgtype.Text
}

func (q *Queries) GetUserInfoByID(ctx context.Context, id int32) (GetUserInfoByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserInfoByID, id)
	var i GetUserInfoByIDRow
	err := row.Scan(
		&i.Column1,
		&i.Email,
		&i.JobTitle,
		&i.DepartmentName,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
select r.code from roles r
join user_roles ur on r.id = ur.role_id
where ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const giveUserRole = `-- name: GiveUserRole :exec
insert into user_roles (user_id, role_id) values ($1, $2)
`

type GiveUserRoleParams struct {
	UserID int32
	RoleID int32
}

func (q *Queries) GiveUserRole(ctx context.Context, arg GiveUserRoleParams) error {
	_, err := q.db.Exec(ctx, giveUserRole, arg.UserID, arg.RoleID)
	return err
}
