// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovalWorkflow struct {
	ID         int32
	RequestID  pgtype.Int4
	ApproverID pgtype.Int4
	StepOrder  int32
	Status     string
	CreatedAt  pgtype.Date
}

type Department struct {
	ID   int32
	Name string
}

type Request struct {
	ID           int32
	ApplicantID  pgtype.Int4
	ResourceID   pgtype.Int4
	AccessType   string
	AccessReason string
	Status       string
	Comments     pgtype.Text
	CreatedAt    pgtype.Date
}

type Resource struct {
	ID           int32
	Name         string
	Description  string
	Resource     string
	ResourceType string
	OwnerID      pgtype.Int4
	CreatedAt    pgtype.Date
}

type Role struct {
	ID   int32
	Code string
	Name string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	DepartmentID int32
	ManagerID    pgtype.Int4
	JobTitle     pgtype.Text
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Date
}

type UserRole struct {
	UserID int32
	RoleID int32
}
