// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Department struct {
	ID   int32
	Name string
}

type Role struct {
	ID   int32
	Code string
	Name string
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	DepartmentID pgtype.Int4
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Date
}

type UserRole struct {
	UserID int32
	RoleID int32
}
