// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovalStep = `-- name: CreateApprovalStep :exec
insert into approval_workflow (request_id, approver_id, step_order, status)
values ($1, $2, $3, $4)
`

type CreateApprovalStepParams struct {
	RequestID  pgtype.Int4
	ApproverID pgtype.Int4
	StepOrder  int32
	Status     string
}

func (q *Queries) CreateApprovalStep(ctx context.Context, arg CreateApprovalStepParams) error {
	_, err := q.db.Exec(ctx, createApprovalStep,
		arg.RequestID,
		arg.ApproverID,
		arg.StepOrder,
		arg.Status,
	)
	return err
}

const createRequest = `-- name: CreateRequest :one
insert into requests (applicant_id, resource_id, access_type, access_reason, status)
values ($1, $2, $3, $4, 'pending') returning id, applicant_id, resource_id, access_type, access_reason, status, comments, created_at
`

type CreateRequestParams struct {
	ApplicantID  pgtype.Int4
	ResourceID   pgtype.Int4
	AccessType   string
	AccessReason string
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ApplicantID,
		arg.ResourceID,
		arg.AccessType,
		arg.AccessReason,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ApplicantID,
		&i.ResourceID,
		&i.AccessType,
		&i.AccessReason,
		&i.Status,
		&i.Comments,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
delete from requests
where id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
select r.id, r.applicant_id, res.id as resource_id, res.name as resource_name, r.access_type, r.access_reason, r.status, r.comments, r.created_at
from requests r
join resources res on r.resource_id = res.id
where r.id = $1
`

type GetRequestByIDRow struct {
	ID           int32
	ApplicantID  pgtype.Int4
	ResourceID   int32
	ResourceName string
	AccessType   string
	AccessReason string
	Status       string
	Comments     pgtype.Text
	CreatedAt    pgtype.Date
}

func (q *Queries) GetRequestByID(ctx context.Context, id int32) (GetRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i GetRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApplicantID,
		&i.ResourceID,
		&i.ResourceName,
		&i.AccessType,
		&i.AccessReason,
		&i.Status,
		&i.Comments,
		&i.CreatedAt,
	)
	return i, err
}

const listUserRequests = `-- name: ListUserRequests :many

select r.id, res.id as resource_id, res.name as resource_name, r.access_type, r.access_reason, r.status, r.comments, r.created_at
from requests r
join resources res on r.resource_id = res.id
where r.applicant_id = $1
`

type ListUserRequestsRow struct {
	ID           int32
	ResourceID   int32
	ResourceName string
	AccessType   string
	AccessReason string
	Status       string
	Comments     pgtype.Text
	CreatedAt    pgtype.Date
}

// -- name: ListRequests :many
// select r.id, u.first_name || ' ' || u.last_name as applicant_name, d.name as department_name, res.name as resource_name, r.access_type, r.access_reason, r.status, r.created_at
// from requests r
// join users u on r.applicant_id = u.id
// join departments d on r.department_id = d.id
// join resources res on r.resource_id = res.id;
func (q *Queries) ListUserRequests(ctx context.Context, applicantID pgtype.Int4) ([]ListUserRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserRequests, applicantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRequestsRow
	for rows.Next() {
		var i ListUserRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.ResourceName,
			&i.AccessType,
			&i.AccessReason,
			&i.Status,
			&i.Comments,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
update requests
set status = $1
where id = $2
`

type UpdateRequestStatusParams struct {
	Status string
	ID     int32
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateRequestStatus, arg.Status, arg.ID)
	return err
}
