// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :exec
insert into resources (name, description, resource, resource_type, owner_id)
values ($1, $2, $3, $4, $5)
`

type CreateResourceParams struct {
	Name         string
	Description  string
	Resource     string
	ResourceType string
	OwnerID      pgtype.Int4
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) error {
	_, err := q.db.Exec(ctx, createResource,
		arg.Name,
		arg.Description,
		arg.Resource,
		arg.ResourceType,
		arg.OwnerID,
	)
	return err
}

const listResources = `-- name: ListResources :many
select r.id, r.name, r.description, r.resource_type
from resources r
`

type ListResourcesRow struct {
	ID           int32
	Name         string
	Description  string
	ResourceType string
}

func (q *Queries) ListResources(ctx context.Context) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListResourcesRow
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ResourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
